# Generated by Django 5.1.7 on 2025-04-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('description', models.TextField(blank=True, null=True)),
                ('escolha', models.CharField(choices=[('CPFL', 'CPFL'), ('Naturgy', 'Naturgy'), ('Energisa', 'Energisa'), ('Vivo', 'Vivo')], default='CPFL', max_length=50)),
                ('boleto_data', models.DateField(blank=True, max_length=10, null=True)),
                ('boleto_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['boleto_data'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pics', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
