# Generated by Django 5.1.7 on 2025-07-10 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_image_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagem',
        ),
        migrations.RenameField(
            model_name='imagem',
            old_name='image',
            new_name='imagem',
        ),
    ]
