# Generated by Django 5.1.7 on 2025-07-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_rename_image_imagem_rename_image_imagem_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='escolha',
            new_name='tipo_conta',
        ),
    ]
